Repository UnBParadigmas2021-2/2021.2-G2_Solaire_Disciples_Logical_Hospital_Triage, pull requests merged in 2022-03, with the labels that each got.

#1 Adiciona api e um bucado de coisa
  .gitignore
  api.pl
  list_persistence.pl
  main.pl
Labels: enhancement

#2 Adiciona chamada de paciente
  api.pl
  list_persistence.pl
Labels: enhancement

#3 Adiciona protocolo de manchester
  api.pl
  list_persistence.pl
Labels: enhancement

#4 add relative priority
  api.pl
  list_persistence.pl
Labels: enhancement

#6 Mostrando as filas de pacientes segundo os diferentes critérios de ordenação
  .gitignore
  Makefile
  api.pl
  docker-compose.yml
  front-docker
  front/.gitignore
  front/README.md
  front/package.json
  front/public/favicon.ico
  front/public/index.html
  front/public/logo192.png
  front/public/logo512.png
  front/public/manifest.json
  front/public/robots.txt
  front/src/App.css
  front/src/App.js
  front/src/App.test.js
  front/src/components/Table/Table.js
  front/src/index.css
  front/src/index.js
  front/src/logo.svg
  front/src/reportWebVitals.js
  front/src/services/api.js
  front/src/setupTests.js
  front/yarn.lock
Labels: enhancement

#7 Feat/input based manchester
  list_persistence.pl
  triage_category.pl
Labels: enhancement

#8 Feat/front patient lists
  front/src/App.css
  front/src/App.js
  front/src/components/Table/Table.js
  list_persistence.pl
Labels: enhancement

#13 Atualizando o README
  README.md
  imgs/arrival.png
  imgs/inicial.png
  imgs/manchester.png
  imgs/relativa.png
Labels: documentation, enhancement

#12 add calling patient and popping list api call and button
  front/src/App.css
  front/src/App.js
Labels: enhancement

#15 Adiciona card para forms de anamnese
  front/src/App.js
Labels: enhancement

#16 Docs/readme
  README.md
Labels: documentation

#17 Feat/front end final touches
  front/src/App.css
  front/src/App.js
  front/src/components/Table/Table.js
Labels: enhancement

#18 fix: corrige medium pain assert
  triage_category.pl
Labels: bug

#19 refactor unuseful code and add comments to functions
  front/src/App.js
Labels: enhancement
